### ISSUE TITLE
Proper support for multiple commanders needed

### ISSUE THREAD

**Issue by Skasi** [ZeroK-RTS/Zero-K#1112]
When players start with two commanders they should be able to select different chassis and starting positions for both.

There are multiple occasions that need to be handled. Players might start with commanders from afkers or just get extra comms because of uneven teams.

**Comment by Licho1** [comment]
Sounds pretty advanced/rare feature ..
Read: low priority

**Comment by Skasi** [comment]
Not rare at all. This is needed almost every other teamgame.

**Comment by sprunk** [comment]
The proper fix is to have a matchmaker that does not allow uneven teams.

**Comment by Skasi** [comment]
Like I said, "There are multiple occasions that need to be handled." Your "solution" wont magically prevent people from being afk/DC/unable to join and thus not getting to pick a commander/spawn location.

**Comment by sprunk** [comment]
The other situations aren't created by the system.

They can appear at any time before extra comms spawn: there still need to be sensible defaults because it's possible for the issue to pop up in the last moment. With decent defaults the handling is of very low priority because AFKers are less likely to happen with a decent matchmaker (cycling happens faster, maybe there's some active confirmation etc.) and DC / not loading are rare.

The startpos choice is partially fixed by the new startbox API which allows to make sure extra comms spawn in a sensible place instead of the middle of the box.

The chassis choice would be solved by dynamic comms.

**Comment by sprunk** [comment]
Fixed by dynamic comms

**Comment by Skasi** [comment]
Players still can't pick multiple chassis and starting positions.
