### ISSUE TITLE
After load odd things happen

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#1937]
- units can move through preexisting units (vehicle cons through other vehcons and powerplants, antinuke)
- one missile insta exploded on the launch pad (possibly it was launched during save)
- one missile got stuck beyond map with extremely high emp timer (might be the same one).

http://i.imgur.com/XeQFuV0.png

[Saves.zip](https://github.com/ZeroK-RTS/Zero-K/files/772236/Saves.zip)

**Comment by KingRaptor** [comment]
Missile issues should be fixed by https://github.com/ZeroK-RTS/Zero-K/commit/a2ee541503993f04bfec9016d4d05ccc5df4d7d0

**Comment by The-Yak** [comment]
This is no longer an issue?

**Comment by sprunk** [comment]
Nothing seems to have been done to "units can move through preexisting units" so it's presumably still an issue.
