### ISSUE TITLE
BCV Skydust: height eyedropper mode

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K#1991]
with previously terraform UI you hold CTRL down, then move mous to desired land position to capture the height and click to start terraform.

how to do this with the 'b' UI mode? c,v to raise lower...

**Comment by GoogleFrog** [comment]
'b' and c/v to raise/lower.

**Comment by sprunk** [comment]
The question has been answered but it reveals a discoverability problem.

**Comment by mojjj** [comment]
'c' to raise, 'b' to lower is NOT what i meant. i already stated this above.

use 'b' to enable terra mode. THEN i want to set the height to a specific height of a point of the map.

OLD terraform allowed the following (enable in settings the option: building hold mouse to start to terraform): 
1) select a building from build menu, 
2) click and hold mouse at desired build site => terraform mode enabled. 
3) hold CTRL key and move mouse to a position on the map. 
4) click with left mouse to lock height of cursor to target height of terraform of building. 

result: building space is terraformed to desired height then building is built at this location

**Comment by GoogleFrog** [comment]
Done.

**Comment by sprunk** [comment]
To be precise: BCV still does not have eyedropper mode but the mouse-based terraform (which can do eyedropper) is now enabled by default.
