### ISSUE TITLE
Errors in the mission "Tutorial - Running Start" infolog.txt

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#734]
There appears to be something wrong with modfonts and mission_runner.

infolog.txt: https://gist.github.com/Sgathec/c9f017a4081d534e14b3

**Comment by Sgathec** [comment]
Alright, the modfonts thing is caused by Display DPS.

**Comment by GoogleFrog** [comment]
Sounds like it is time to delete that widget.

**Comment by xponen** [comment]
its non-default and can be fixed.
@Sgathec was using it

I'll debug

**Comment by xponen** [comment]
This has been fixed 2 years ago:
https://github.com/ZeroK-RTS/Zero-K/commit/ac3683c012a229493b117e422233fd0b0b5768a9#diff-bb60b9fbaecb1e7740c74af1f0e27947L159

Recommend:
The modfont.lua in "Tutorial - Running Start r318.sdz" to be removed so that widget can use the latest version from Zero-K

**Comment by KingRaptor** [comment]
Is mission uploading still broken? If it is, someone will have to find a way to manually accomplish this.

**Comment by xponen** [comment]
Can you tell me where I can try to upload/replace the file?

**Comment by KingRaptor** [comment]
The file for each mission is stored as a base64 (AFAIK, check the mission uploader service to be sure?) string in the Missions DB table, replace that.

**Comment by sprunk** [comment]
Not a ZK problem: the mission is outdated (see https://github.com/ZeroK-RTS/Zero-K-Missions/issues/5). Closable.

**Comment by KingRaptor** [comment]
Every mission has modfonts.lua (the editor includes it). Does this issue also appear on other missions?

**Comment by Sgathec** [comment]
I didn't find "modfont" in the infolog with the search function after opening and exiting Tutorial 2.

**Comment by KingRaptor** [comment]
Tutorial 1 was updated in any case, so I'll close this. 
Reopen if issue is still around.
